

# <center>Welcome in Branch and Bound Applied to FSP</center>

### Packages importing & data loading

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
from utils_branch_bound import read_flow_shop_data

In [13]:
instances = read_flow_shop_data('./../data/tai20_5.txt', 5, 20)

In [14]:
instances

[(5,
  20,
  array([[54, 83, 15, 71, 77, 36, 53, 38, 27, 87, 76, 91, 14, 29, 12, 77,
          32, 87, 68, 94],
         [79,  3, 11, 99, 56, 70, 99, 60,  5, 56,  3, 61, 73, 75, 47, 14,
          21, 86,  5, 77],
         [16, 89, 49, 15, 89, 45, 60, 23, 57, 64,  7,  1, 63, 41, 63, 47,
          26, 75, 77, 40],
         [66, 58, 31, 68, 78, 91, 13, 59, 49, 85, 85,  9, 39, 41, 56, 40,
          54, 77, 51, 31],
         [58, 56, 20, 85, 53, 35, 53, 41, 69, 13, 86, 72,  8, 49, 47, 87,
          58, 18, 68, 28]])),
 (5,
  20,
  array([[26, 38, 27, 88, 95, 55, 54, 63, 23, 45, 86, 43, 43, 40, 37, 54,
          35, 59, 43, 50],
         [59, 62, 44, 10, 23, 64, 47, 68, 54,  9, 30, 31, 92,  7, 14, 95,
          76, 82, 91, 37],
         [78, 90, 64, 49, 47, 20, 61, 93, 36, 47, 70, 54, 87, 13, 40, 34,
          55, 13, 11,  5],
         [88, 54, 47, 83, 84,  9, 30, 11, 92, 63, 62, 75, 48, 23, 85, 23,
           4, 31, 13, 98],
         [69, 30, 61, 35, 53, 98, 94, 33, 77, 31, 54, 71, 78,  9, 

### Test with a simple instance

In [15]:
from utils_branch_bound import FlowShopBranchBoundSolver
from utils_branch_bound import johnson_method
from utils_branch_bound import all_permutations

In [16]:
instance_test =  '''\
20 5 873654221 1278 1232
54 83 15 71 77
79  3 11 99 56
16 89 49 15 89
'''
instance_array = np.array([
    [54, 83, 15, 71, 77],
    [79, 3, 11, 99, 56],
    [16, 89, 49, 15, 89]
])

In [17]:
solver = FlowShopBranchBoundSolver()

solver.consider_instance(instance_array)

solver.solve(list(range(5)))
bound, incremental_cost = solver.compute_lower_bound(list(range(5)))


print("makspan :",solver.bound)
print("Solution :", solver.intial_solution)

makspan : 373.0
Solution : [2, 1, 3, 4, 0]


In [18]:
all_p = all_permutations(list(range(5)))
print(all_p)

[[0, 1, 2, 3, 4], [0, 1, 2, 4, 3], [0, 1, 3, 2, 4], [0, 1, 3, 4, 2], [0, 1, 4, 2, 3], [0, 1, 4, 3, 2], [0, 2, 1, 3, 4], [0, 2, 1, 4, 3], [0, 2, 3, 1, 4], [0, 2, 3, 4, 1], [0, 2, 4, 1, 3], [0, 2, 4, 3, 1], [0, 3, 1, 2, 4], [0, 3, 1, 4, 2], [0, 3, 2, 1, 4], [0, 3, 2, 4, 1], [0, 3, 4, 1, 2], [0, 3, 4, 2, 1], [0, 4, 1, 2, 3], [0, 4, 1, 3, 2], [0, 4, 2, 1, 3], [0, 4, 2, 3, 1], [0, 4, 3, 1, 2], [0, 4, 3, 2, 1], [1, 0, 2, 3, 4], [1, 0, 2, 4, 3], [1, 0, 3, 2, 4], [1, 0, 3, 4, 2], [1, 0, 4, 2, 3], [1, 0, 4, 3, 2], [1, 2, 0, 3, 4], [1, 2, 0, 4, 3], [1, 2, 3, 0, 4], [1, 2, 3, 4, 0], [1, 2, 4, 0, 3], [1, 2, 4, 3, 0], [1, 3, 0, 2, 4], [1, 3, 0, 4, 2], [1, 3, 2, 0, 4], [1, 3, 2, 4, 0], [1, 3, 4, 0, 2], [1, 3, 4, 2, 0], [1, 4, 0, 2, 3], [1, 4, 0, 3, 2], [1, 4, 2, 0, 3], [1, 4, 2, 3, 0], [1, 4, 3, 0, 2], [1, 4, 3, 2, 0], [2, 0, 1, 3, 4], [2, 0, 1, 4, 3], [2, 0, 3, 1, 4], [2, 0, 3, 4, 1], [2, 0, 4, 1, 3], [2, 0, 4, 3, 1], [2, 1, 0, 3, 4], [2, 1, 0, 4, 3], [2, 1, 3, 0, 4], [2, 1, 3, 4, 0], [2, 1, 4, 0, 

In [19]:
import math
bound = math.inf
solution = None
for i in all_p:
    gg, _ = solver.compute_lower_bound(i)
    if gg < bound:
        bound = gg
        solution = i
        
print("makspan :",bound)
print("Solution :", solution)

makspan : 373.0
Solution : [2, 1, 3, 4, 0]


### Test B&B with First solution using Johnson

In [26]:
solution = johnson_method(instances[0][2][:2, :8].T)
makspan, _ = solver.compute_lower_bound(solution)

print("makspan :",makspan)
print("Solution :", solution)

makspan : 526.0
Solution : [5, 7, 6, 0, 3, 4, 2, 1]


In [28]:
''' this is only to confirm that our branch and bound is working correctly comparing to
the solution of the johnson method for 2 machine flowshop problem

'''
solver = FlowShopBranchBoundSolver()


solver.consider_instance(instances[0][2][:2,:8])


solver.solve(list(range(8)))

makspan, _ = solver.compute_lower_bound(solver.intial_solution)

print("makspan :",makspan)
print("Solution :", solution)

# print(solver.intial_solution)

makspan : 526.0
Solution : [5, 7, 6, 0, 3, 4, 2, 1]


In [ ]:

solver = FlowShopBranchBoundSolver()


solver.consider_instance(instances[0][2][:,:8])


solver.solve(list(range(8)))

makspan, _ = solver.compute_lower_bound(solver.intial_solution)

print("makspan :",makspan)
print("Solution :", solution)

# print(solver.intial_solution)

In [ ]:
print(solver.intial_solution)
solver.bound
solver.incremental_cost

[5, 0, 2, 3, 4, 6, 1, 7]


array([[ 38., 121., 136., 207., 284., 320., 373., 411.],
       [ 98., 220., 290., 346., 445., 456., 459., 538.]])

### Test with benchmark tai **20**_**5**

In [37]:
johnson_solution = johnson_method(instances[0][2][:2, :].T)
solver.consider_instance(instances[0][2])
makspan, _ = solver.compute_lower_bound(johnson_solution)

print("makspan :",makspan)
print("Solution :", johnson_solution)

makspan : 1659.0
Solution : [14, 12, 13, 5, 7, 6, 0, 3, 17, 19, 11, 9, 4, 16, 15, 2, 18, 8, 10, 1]


In [38]:
solver = FlowShopBranchBoundSolver()


solver.consider_instance(instances[0][2])


solver.solve(johnson_solution)

makspan, _ = solver.compute_lower_bound(solver.intial_solution)

print("makspan :",makspan)
print("Solution :", solution)

### Ploting of gantt of the results

In [ ]:
def plot_gantt(tasks):
    fig, ax = plt.subplots(figsize=(10, 5))

    for i, task in enumerate(tasks):
        ax.barh(i, task['end'] - task['start'], left=task['start'], height=0.3, align='center', label=task['label'])

    ax.set_yticks(range(len(tasks)))
    ax.set_yticklabels([task['label'] for task in tasks])
    ax.set_xlabel('Time')
    ax.set_title('Gantt Chart')

    plt.show()

In [ ]:
solution = solver.intial_solution
tasks = []

for i, job in enumerate(solution):
    start_time = solver.incremental_cost[0][i]
    end_time = solver.incremental_cost[1][i]
    tasks.append({'label': f'Task {job}', 'start': start_time, 'end': end_time})



plot_gantt(tasks)


# tasks = [
#     {'label': 'Task 1', 'start': 0, 'end': 5},
#     {'label': 'Task 2', 'start': 3, 'end': 8},
#     {'label': 'Task 3', 'start': 6, 'end': 11}
# ]

# plot_gantt(tasks)

NameError: name 'plot_gantt' is not defined