

# <center>Welcome in Branch and Bound Applied to FSP</center>

### Packages importing & data loading

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

C:\Users\DSI\AppData\Local\Temp\ipykernel_27760\2151744951.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
from utils_branch_bound import read_flow_shop_data

In [3]:
instances = read_flow_shop_data('./../data/tai20_5.txt', 5, 20)

In [4]:
instances

[(5,
  20,
  array([[54, 83, 15, 71, 77, 36, 53, 38, 27, 87, 76, 91, 14, 29, 12, 77,
          32, 87, 68, 94],
         [79,  3, 11, 99, 56, 70, 99, 60,  5, 56,  3, 61, 73, 75, 47, 14,
          21, 86,  5, 77],
         [16, 89, 49, 15, 89, 45, 60, 23, 57, 64,  7,  1, 63, 41, 63, 47,
          26, 75, 77, 40],
         [66, 58, 31, 68, 78, 91, 13, 59, 49, 85, 85,  9, 39, 41, 56, 40,
          54, 77, 51, 31],
         [58, 56, 20, 85, 53, 35, 53, 41, 69, 13, 86, 72,  8, 49, 47, 87,
          58, 18, 68, 28]])),
 (5,
  20,
  array([[26, 38, 27, 88, 95, 55, 54, 63, 23, 45, 86, 43, 43, 40, 37, 54,
          35, 59, 43, 50],
         [59, 62, 44, 10, 23, 64, 47, 68, 54,  9, 30, 31, 92,  7, 14, 95,
          76, 82, 91, 37],
         [78, 90, 64, 49, 47, 20, 61, 93, 36, 47, 70, 54, 87, 13, 40, 34,
          55, 13, 11,  5],
         [88, 54, 47, 83, 84,  9, 30, 11, 92, 63, 62, 75, 48, 23, 85, 23,
           4, 31, 13, 98],
         [69, 30, 61, 35, 53, 98, 94, 33, 77, 31, 54, 71, 78,  9, 

### Test with a simple instance

In [5]:
from utils_branch_bound import FlowShopBranchBoundSolver
# from utils_branch_bound import johnson_method
# from utils_branch_bound import all_permutations

In [6]:
instance_test =  '''\
5 3 873654221 1278 1232
54 83 15 71 77
79  3 11 99 56
16 89 49 15 89
'''
instance_array = np.array([
    [54, 83, 15, 71, 77],
    [79, 3, 11, 99, 56],
    [16, 89, 49, 15, 89]
])

np.array(instance_array)

array([[54, 83, 15, 71, 77],
       [79,  3, 11, 99, 56],
       [16, 89, 49, 15, 89]])

In [7]:
solver = FlowShopBranchBoundSolver()

solver.consider_instance(instance_array)

solver.solve(list(range(5)))

bound = \
    solver.compute_lower_bound(list(range(5)))


print("makspan :",solver.bound)
print("Solution :", solver.intial_solution)

Optimal Solution: [2, 4, 3, 1, 0]
Optimal Cost: 395.0
makspan : 395.0
Solution : [2, 4, 3, 1, 0]


In [8]:
all_p = solver.all_permutations(list(range(5)))
print(all_p)

[[0, 1, 2, 3, 4], [0, 1, 2, 4, 3], [0, 1, 3, 2, 4], [0, 1, 3, 4, 2], [0, 1, 4, 2, 3], [0, 1, 4, 3, 2], [0, 2, 1, 3, 4], [0, 2, 1, 4, 3], [0, 2, 3, 1, 4], [0, 2, 3, 4, 1], [0, 2, 4, 1, 3], [0, 2, 4, 3, 1], [0, 3, 1, 2, 4], [0, 3, 1, 4, 2], [0, 3, 2, 1, 4], [0, 3, 2, 4, 1], [0, 3, 4, 1, 2], [0, 3, 4, 2, 1], [0, 4, 1, 2, 3], [0, 4, 1, 3, 2], [0, 4, 2, 1, 3], [0, 4, 2, 3, 1], [0, 4, 3, 1, 2], [0, 4, 3, 2, 1], [1, 0, 2, 3, 4], [1, 0, 2, 4, 3], [1, 0, 3, 2, 4], [1, 0, 3, 4, 2], [1, 0, 4, 2, 3], [1, 0, 4, 3, 2], [1, 2, 0, 3, 4], [1, 2, 0, 4, 3], [1, 2, 3, 0, 4], [1, 2, 3, 4, 0], [1, 2, 4, 0, 3], [1, 2, 4, 3, 0], [1, 3, 0, 2, 4], [1, 3, 0, 4, 2], [1, 3, 2, 0, 4], [1, 3, 2, 4, 0], [1, 3, 4, 0, 2], [1, 3, 4, 2, 0], [1, 4, 0, 2, 3], [1, 4, 0, 3, 2], [1, 4, 2, 0, 3], [1, 4, 2, 3, 0], [1, 4, 3, 0, 2], [1, 4, 3, 2, 0], [2, 0, 1, 3, 4], [2, 0, 1, 4, 3], [2, 0, 3, 1, 4], [2, 0, 3, 4, 1], [2, 0, 4, 1, 3], [2, 0, 4, 3, 1], [2, 1, 0, 3, 4], [2, 1, 0, 4, 3], [2, 1, 3, 0, 4], [2, 1, 3, 4, 0], [2, 1, 4, 0, 

In [9]:
import math
bound = math.inf
solution = None
for i in all_p:
    gg = solver.compute_lower_bound(i)
    if gg < bound:
        bound = gg
        solution = i
        
print("makspan :",bound)
print("Solution :", solution)

makspan : 395.0
Solution : [2, 4, 3, 1, 0]


### Test B&B with First solution using Johnson and NEH

In [10]:
from utils_branch_bound import johnson_method
solver.consider_instance(instances[0][2][:2, :8])
solution = johnson_method(instances[0][2][:2, :8].T)

makspan = solver.compute_lower_bound(solution)

print("makspan :",makspan)
print("Solution :", solution)

makspan : 513.0
Solution : [5, 7, 6, 0, 3, 4, 2, 1]


In [11]:
''' this is only to confirm that our branch and bound is working correctly comparing to
the solution of the johnson method for 2 machine flowshop problem

'''
solver = FlowShopBranchBoundSolver()


solver.consider_instance(instances[0][2][:2,:8])


solver.solve(list(range(8)))

makspan = solver.compute_lower_bound(solver.intial_solution)

print("makspan :",makspan)
print("Solution :", solution)

# print(solver.intial_solution)

Optimal Solution: [5, 0, 2, 3, 1, 7, 6, 4]
Optimal Cost: 513.0
makspan : 513.0
Solution : [5, 7, 6, 0, 3, 4, 2, 1]


In [12]:

solver = FlowShopBranchBoundSolver()


solver.consider_instance(instances[0][2][:,:8])


solver.solve(list(range(8)))

makspan = solver.compute_lower_bound(solver.intial_solution)

print("makspan :",makspan)
print("Solution :", solution)

# print(solver.intial_solution)

Optimal Solution: [2, 5, 0, 3, 1, 7, 4, 6]
Optimal Cost: 704.0
makspan : 704.0
Solution : [5, 7, 6, 0, 3, 4, 2, 1]


### Test with benchmark tai **20**_**5**

In [13]:
johnson_solution = johnson_method(instances[0][2][:2, :].T)
solver.consider_instance(instances[0][2])
makspan = solver.compute_lower_bound(johnson_solution)

print("makspan :",makspan)
print("Solution :", johnson_solution)

makspan : 1623.0
Solution : [14, 12, 13, 5, 7, 6, 0, 3, 17, 19, 11, 9, 4, 16, 15, 2, 18, 8, 10, 1]


In [16]:
from utils_2 import NEH

solution_neh, _ = NEH(instances[0][2])

new seq job: 12, iteration 0: [12, 16, 2]
LB job12, iteration 0: 321.0
new seq job: 12, iteration 1: [16, 12, 2]
LB job12, iteration 1: 289.0
new seq job: 12, iteration 2: [16, 2, 12]
LB job12, iteration 2: 247.0
new seq job: 8, iteration 0: [8, 16, 2, 12]
LB job8, iteration 0: 293.0
new seq job: 8, iteration 1: [16, 8, 2, 12]
LB job8, iteration 1: 295.0
new seq job: 8, iteration 2: [16, 2, 8, 12]
LB job8, iteration 2: 311.0
new seq job: 8, iteration 3: [16, 2, 12, 8]
LB job8, iteration 3: 375.0
new seq job: 7, iteration 0: [7, 8, 16, 2, 12]
LB job7, iteration 0: 384.0
new seq job: 7, iteration 1: [8, 7, 16, 2, 12]
LB job7, iteration 1: 347.0
new seq job: 7, iteration 2: [8, 16, 7, 2, 12]
LB job7, iteration 2: 351.0
new seq job: 7, iteration 3: [8, 16, 2, 7, 12]
LB job7, iteration 3: 355.0
new seq job: 7, iteration 4: [8, 16, 2, 12, 7]
LB job7, iteration 4: 366.0
new seq job: 14, iteration 0: [14, 8, 7, 16, 2, 12]
LB job14, iteration 0: 427.0
new seq job: 14, iteration 1: [8, 14, 7, 16

In [17]:
solver = FlowShopBranchBoundSolver()
solver.consider_instance(instances[0][2])
solver.solve(solution_neh)
makspan = solver.compute_lower_bound(solver.intial_solution)

print("makspan :",makspan)
print("Solution :", solution)

### Ploting of gantt of the results

In [ ]:
solver.generate_gantt_chart(solution)